config/routes.rb
Rails.application.routes.draw do
  resources :page_infos
  resources :images
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "sessions#new"

  namespace :api do
    namespace :v1 do
      resources :page_infos, only: [:show]
      resources :answers, only: [:create]
    end
  end

  resources :sessions, only: [:new, :create]
  get '/login', to: "sessions#new", as: :login
  match '/logout', to: "sessions#destroy", via: [:get, :delete], as: :logout
end

app/models/page_info.rb
class PageInfo < ApplicationRecord
  validates :name, presence: true, uniqueness: { scope: :locale }
  validates :locale, presence: true
  validates :content, presence: true
end

app/controllers/api/v1/page_infos_controller.rb
class Api::V1::PageInfosController < Api::ApplicationController
  before_action :load_page_info, only: [:show]

  # get /api/v1/page_infos/:id (id is name or id)
  # name in %w(homepage question)
  def show
    if @page_info
      render json: {
        status: SUCCESS_STATUS,
        data: @page_info
      }
    else
      render json: {
        status: ERROR_STATUS,
        message: I18n.t("page_infos.api.v1.not_found")
      }
    end
  end

  private

  def load_page_info
    locale = lode_locale
    @page_info = PageInfo.find_by(name: params[:id], locale: locale) ||
      PageInfo.find_by(id: params[:id], locale: locale)
  end

  # params[:info_locale] will overwrite locale column
  def lode_locale
    params[:info_locale] || I18n.locale
  end
end

app/controllers/page_infos_controller.rb
class PageInfosController < ApplicationController
  before_action :set_page_info, only: [:show, :edit, :update, :destroy]

  # GET /page_infos
  # GET /page_infos.json
  def index
    @page_infos = PageInfo.all
  end

  # GET /page_infos/1
  # GET /page_infos/1.json
  def show
  end

  # GET /page_infos/new
  def new
    @page_info = PageInfo.new
  end

  # GET /page_infos/1/edit
  def edit
  end

  # POST /page_infos
  # POST /page_infos.json
  def create
    @page_info = PageInfo.new(page_info_params)
    @page_info.content = content_param

    respond_to do |format|
      if @page_info.save
        format.html { redirect_to @page_info, notice: 'Page info was successfully created.' }
        format.json { render :show, status: :created, location: @page_info }
      else
        format.html { render :new }
        format.json { render json: @page_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /page_infos/1
  # PATCH/PUT /page_infos/1.json
  def update
    respond_to do |format|
      if @page_info.update(name: params[:page_info][:name], locale: params[:page_info][:locale], content: content_param)
        format.html { redirect_to @page_info, notice: 'Page info was successfully updated.' }
        format.json { render :show, status: :ok, location: @page_info }
      else
        format.html { render :edit }
        format.json { render json: @page_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /page_infos/1
  # DELETE /page_infos/1.json
  def destroy
    @page_info.destroy
    respond_to do |format|
      format.html { redirect_to page_infos_url, notice: 'Page info was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_page_info
      @page_info = PageInfo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def page_info_params
      params.require(:page_info).permit(:name, :locale)
    end

    def content_param
      Oj.load(params[:page_info][:content])
    rescue
      nil
    end
end

app/helpers/api/v1/page_infos_helper.rb
module Api::V1::PageInfosHelper
end

app/helpers/page_infos_helper.rb
module PageInfosHelper
end

app/views/page_infos/_form.html.erb
<%= form_with(model: page_info, local: true) do |form| %>
  <% if page_info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(page_info.errors.count, "error") %> prohibited this page_info from being saved:</h2>

      <ul>
      <% page_info.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :locale %>
    <%= form.text_field :locale %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <div id="jsoneditor" style="width: 400px; height: 400px;"></div>
    <%= form.text_area :content, id: "content", style: "height: 200px; width: 800px;", hidden: true, data: { content: "#{Oj.dump(@page_info.content)}" } %>
  </div>

  <div class="actions">
    <%= form.submit "Submit", id: "submit-page-info" %>
  </div>
<% end %>

app/views/page_infos/edit.html.erb
<h1>Editing Page Info</h1>

<%= render 'form', page_info: @page_info %>

<%= link_to 'Show', @page_info %> |
<%= link_to 'Back', page_infos_path %>

app/views/page_infos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Page Infos</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Locale</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @page_infos.each do |page_info| %>
      <tr>
        <td><%= page_info.name %></td>
        <td><%= page_info.locale %></td>
        <td><%= page_info.content %></td>
        <td><%= link_to 'Show', page_info %></td>
        <td><%= link_to 'Edit', edit_page_info_path(page_info) %></td>
        <td><%= link_to 'Destroy', page_info, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Page Info', new_page_info_path %>

app/views/page_infos/new.html.erb
<h1>New Page Info</h1>

<%= render 'form', page_info: @page_info %>

<%= link_to 'Back', page_infos_path %>

app/views/page_infos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @page_info.name %>
</p>

<p>
  <strong>Locale:</strong>
  <%= @page_info.locale %>
</p>

<p>
  <strong>Content:</strong>
  <%= @page_info.content %>
</p>

<%= link_to 'Edit', edit_page_info_path(@page_info) %> |
<%= link_to 'Back', page_infos_path %>