config/routes.rb
Rails.application.routes.draw do
  resources :page_infos
  resources :images
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "sessions#new"

  namespace :api do
    namespace :v1 do
      resources :page_infos, only: [:show]
      resources :answers, only: [:create]
    end
  end

  resources :sessions, only: [:new, :create]
  get '/login', to: "sessions#new", as: :login
  match '/logout', to: "sessions#destroy", via: [:get, :delete], as: :logout
end

app/views/layouts/_header.html.erb
<header class="header-box">

  <div class="header-limiter">
    <nav>
      <a href="<%= images_path %>">Images</a>
      <a href="<%= page_infos_path %>">PageInfos</a>

      <% if logged_in? %>
        <a href="<%= logout_path %>">Log out</a>
      <% else %>
        <a href="<%= login_path %>">Log in</a>
      <% end %>
    </nav>
  </div>

</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NervosCitaServer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%#= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" unless params[:controller] == "sessions" %>
    <%= yield %>
  </body>
</html>